#!/bin/sh

DATE=$1
POLICY="${USER}.${DATE}"

if [ -z $DATE ]
then
	echo "$0 <DATE>"
	exit
fi

if [ -f $POLICY ]
then
	for KEY in $(grep ^pub ${POLICY} |grep -v revoked: |awk '{print$2}'|awk -F/ '{print $2}'|xargs)
	do
		if [ ! -f "$POLICY.$KEY.sig" ]
		then
			gpg -qbu ${KEY}! ${POLICY}
			if [ -f "$POLICY.asc" ]
			then
				mv ${POLICY}.asc ${POLICY}.${KEY}.sig
				gpg --verify ${POLICY}.${KEY}.sig ${POLICY}
			else
				echo "Bad signature for $KEY"
			fi
		fi
	done
	
fi
